# Generated by Django 5.2.3 on 2025-06-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_rename_imagen_alumnos_img_comentarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentarios',
            new_name='Comentario',
        ),
    ]
