# Generated by Django 5.2.3 on 2025-06-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_alter_comentario_coment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='matricula',
            field=models.CharField(max_length=12, verbose_name='Matricula'),
        ),
    ]
