# Generated by Django 5.2.3 on 2025-07-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0007_alter_alumnos_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioContacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('usuario', models.TextField(verbose_name='Usuario')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
            ],
            options={
                'verbose_name': 'Comentario de Contacto',
                'verbose_name_plural': 'Comentarios de Contacto',
                'ordering': ['-create'],
            },
        ),
    ]
