# Generated by Django 5.2.3 on 2025-07-04 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0008_comentariocontacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentariocontacto',
            options={'ordering': ['-created'], 'verbose_name': 'Comentario de Contacto', 'verbose_name_plural': 'Comentarios de Contacto'},
        ),
        migrations.RenameField(
            model_name='comentariocontacto',
            old_name='create',
            new_name='created',
        ),
    ]
