# Generated by Django 5.2.3 on 2025-06-29 16:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Título del Curso')),
                ('descripcion', models.TextField(verbose_name='Descripción Detallada')),
                ('duracion_horas', models.IntegerField(verbose_name='Duración (en horas)')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Costo de Inscripción (MXN)')),
                ('publicado', models.BooleanField(default=False, verbose_name='¿Está publicado?')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursos/imagenes/', verbose_name='Imagen Promocional')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['created'],
            },
        ),
    ]
