# Generated by Django 5.2.3 on 2025-06-29 17:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=ckeditor.fields.RichTextField(verbose_name='Descripción Detallada'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracion_horas',
            field=models.IntegerField(verbose_name='Duración'),
        ),
    ]
