# Generated by Django 5.2.3 on 2025-06-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_curso_descripcion_alter_curso_duracion_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='duracion_horas',
            field=models.IntegerField(verbose_name='Duración (en horas)'),
        ),
    ]
