# Generated by Django 5.2.3 on 2025-07-01 20:31

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_curso_duracion_horas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave de la Actividad')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Descripción de la Actividad')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso', verbose_name='Curso al que Pertenece')),
            ],
            options={
                'verbose_name': 'Actividad del Curso',
                'verbose_name_plural': 'Actividades del Curso',
                'ordering': ['-created'],
            },
        ),
    ]
