# Generated by Django 5.2.3 on 2025-07-04 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_actividad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['-created'], 'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
    ]
